name: flutter_rasp_example
description: "Demonstrates how to use the flutter_rasp plugin."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_rasp:
    path: ../
  dio: ^5.9.1
  http: ^1.6.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/certs/
