name: flutter_rasp
description: "RASP plugin for Flutter. Detect root, jailbreak, emulators, debuggers, hooks, repackaging, VPN, SSL pinning, and more."
version: 5.0.1
homepage: https://juandpt.dev
repository: https://github.com/juandpt03/flutter_rasp
issue_tracker: https://github.com/juandpt03/flutter_rasp/issues
topics:
  - security
  - rasp
  - ssl-pinning
  - root-detection
  - flutter-plugin

environment:
  sdk: ^3.11.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  pointycastle: ^3.9.1
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.3.3

flutter:
  plugin:
    platforms:
      android:
        package: com.juandpt.flutter_rasp
        pluginClass: FlutterRaspPlugin
      ios:
        pluginClass: FlutterRaspPlugin
