// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.juandpt.flutter_rasp

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object RaspApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class AndroidConfigMessage (
  val signingCertHashes: List<String>,
  val supportedStores: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidConfigMessage {
      val signingCertHashes = pigeonVar_list[0] as List<String>
      val supportedStores = pigeonVar_list[1] as List<String>
      return AndroidConfigMessage(signingCertHashes, supportedStores)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      signingCertHashes,
      supportedStores,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidConfigMessage
    return RaspApiPigeonUtils.deepEquals(this.signingCertHashes, other.signingCertHashes) && RaspApiPigeonUtils.deepEquals(this.supportedStores, other.supportedStores)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.signingCertHashes)
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.supportedStores)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class IosConfigMessage (
  val teamId: String,
  val bundleIds: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IosConfigMessage {
      val teamId = pigeonVar_list[0] as String
      val bundleIds = pigeonVar_list[1] as List<String>
      return IosConfigMessage(teamId, bundleIds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      teamId,
      bundleIds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IosConfigMessage
    return RaspApiPigeonUtils.deepEquals(this.teamId, other.teamId) && RaspApiPigeonUtils.deepEquals(this.bundleIds, other.bundleIds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.teamId)
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.bundleIds)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RaspConfigMessage (
  val enabledThreats: List<String>,
  val exitThreats: List<String>,
  val monitoringIntervalMs: Long,
  val androidConfig: AndroidConfigMessage? = null,
  val iosConfig: IosConfigMessage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RaspConfigMessage {
      val enabledThreats = pigeonVar_list[0] as List<String>
      val exitThreats = pigeonVar_list[1] as List<String>
      val monitoringIntervalMs = pigeonVar_list[2] as Long
      val androidConfig = pigeonVar_list[3] as AndroidConfigMessage?
      val iosConfig = pigeonVar_list[4] as IosConfigMessage?
      return RaspConfigMessage(enabledThreats, exitThreats, monitoringIntervalMs, androidConfig, iosConfig)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enabledThreats,
      exitThreats,
      monitoringIntervalMs,
      androidConfig,
      iosConfig,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RaspConfigMessage
    return RaspApiPigeonUtils.deepEquals(this.enabledThreats, other.enabledThreats) && RaspApiPigeonUtils.deepEquals(this.exitThreats, other.exitThreats) && RaspApiPigeonUtils.deepEquals(this.monitoringIntervalMs, other.monitoringIntervalMs) && RaspApiPigeonUtils.deepEquals(this.androidConfig, other.androidConfig) && RaspApiPigeonUtils.deepEquals(this.iosConfig, other.iosConfig)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.enabledThreats)
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.exitThreats)
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.monitoringIntervalMs)
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.androidConfig)
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.iosConfig)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ThreatResultEntry (
  val threatName: String,
  val detected: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ThreatResultEntry {
      val threatName = pigeonVar_list[0] as String
      val detected = pigeonVar_list[1] as Boolean
      return ThreatResultEntry(threatName, detected)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      threatName,
      detected,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ThreatResultEntry
    return RaspApiPigeonUtils.deepEquals(this.threatName, other.threatName) && RaspApiPigeonUtils.deepEquals(this.detected, other.detected)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.threatName)
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.detected)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScanResultMessage (
  val results: List<ThreatResultEntry>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanResultMessage {
      val results = pigeonVar_list[0] as List<ThreatResultEntry>
      return ScanResultMessage(results)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      results,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScanResultMessage
    return RaspApiPigeonUtils.deepEquals(this.results, other.results)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + RaspApiPigeonUtils.deepHash(this.results)
    return result
  }
}
private open class RaspApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidConfigMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IosConfigMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RaspConfigMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ThreatResultEntry.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanResultMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AndroidConfigMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is IosConfigMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is RaspConfigMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ThreatResultEntry -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ScanResultMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FlutterRaspHostApi {
  fun startMonitoring(config: RaspConfigMessage, callback: (Result<Unit>) -> Unit)
  fun stopMonitoring(callback: (Result<Unit>) -> Unit)
  fun checkThreat(threatName: String, callback: (Result<Boolean>) -> Unit)
  fun scanAll(enabledThreats: List<String>, callback: (Result<ScanResultMessage>) -> Unit)
  fun blockScreenCapture(enabled: Boolean, callback: (Result<Unit>) -> Unit)
  fun isScreenCaptureBlocked(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by FlutterRaspHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      RaspApiPigeonCodec()
    }
    /** Sets up an instance of `FlutterRaspHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterRaspHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.startMonitoring$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as RaspConfigMessage
            api.startMonitoring(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RaspApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(RaspApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.stopMonitoring$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopMonitoring{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RaspApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(RaspApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.checkThreat$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val threatNameArg = args[0] as String
            api.checkThreat(threatNameArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RaspApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RaspApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.scanAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledThreatsArg = args[0] as List<String>
            api.scanAll(enabledThreatsArg) { result: Result<ScanResultMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RaspApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RaspApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.blockScreenCapture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            api.blockScreenCapture(enabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RaspApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(RaspApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.isScreenCaptureBlocked$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isScreenCaptureBlocked{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RaspApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RaspApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class FlutterRaspFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FlutterRaspFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      RaspApiPigeonCodec()
    }
  }
  fun onThreatsDetected(threatsArg: List<String>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_rasp.FlutterRaspFlutterApi.onThreatsDetected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(threatsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(RaspApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
