// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsRaspApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashRaspApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsRaspApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsRaspApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsRaspApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsRaspApi(lhsKey, rhsKey) {
          if deepEqualsRaspApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsRaspApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashRaspApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashRaspApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashRaspApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashRaspApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashRaspApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashRaspApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct AndroidConfigMessage: Hashable {
  var signingCertHashes: [String]
  var supportedStores: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidConfigMessage? {
    let signingCertHashes = pigeonVar_list[0] as! [String]
    let supportedStores = pigeonVar_list[1] as! [String]

    return AndroidConfigMessage(
      signingCertHashes: signingCertHashes,
      supportedStores: supportedStores
    )
  }
  func toList() -> [Any?] {
    return [
      signingCertHashes,
      supportedStores,
    ]
  }
  static func == (lhs: AndroidConfigMessage, rhs: AndroidConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsRaspApi(lhs.signingCertHashes, rhs.signingCertHashes) && deepEqualsRaspApi(lhs.supportedStores, rhs.supportedStores)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AndroidConfigMessage")
    deepHashRaspApi(value: signingCertHashes, hasher: &hasher)
    deepHashRaspApi(value: supportedStores, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct IosConfigMessage: Hashable {
  var teamId: String
  var bundleIds: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IosConfigMessage? {
    let teamId = pigeonVar_list[0] as! String
    let bundleIds = pigeonVar_list[1] as! [String]

    return IosConfigMessage(
      teamId: teamId,
      bundleIds: bundleIds
    )
  }
  func toList() -> [Any?] {
    return [
      teamId,
      bundleIds,
    ]
  }
  static func == (lhs: IosConfigMessage, rhs: IosConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsRaspApi(lhs.teamId, rhs.teamId) && deepEqualsRaspApi(lhs.bundleIds, rhs.bundleIds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IosConfigMessage")
    deepHashRaspApi(value: teamId, hasher: &hasher)
    deepHashRaspApi(value: bundleIds, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RaspConfigMessage: Hashable {
  var enabledThreats: [String]
  var exitThreats: [String]
  var monitoringIntervalMs: Int64
  var androidConfig: AndroidConfigMessage? = nil
  var iosConfig: IosConfigMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RaspConfigMessage? {
    let enabledThreats = pigeonVar_list[0] as! [String]
    let exitThreats = pigeonVar_list[1] as! [String]
    let monitoringIntervalMs = pigeonVar_list[2] as! Int64
    let androidConfig: AndroidConfigMessage? = nilOrValue(pigeonVar_list[3])
    let iosConfig: IosConfigMessage? = nilOrValue(pigeonVar_list[4])

    return RaspConfigMessage(
      enabledThreats: enabledThreats,
      exitThreats: exitThreats,
      monitoringIntervalMs: monitoringIntervalMs,
      androidConfig: androidConfig,
      iosConfig: iosConfig
    )
  }
  func toList() -> [Any?] {
    return [
      enabledThreats,
      exitThreats,
      monitoringIntervalMs,
      androidConfig,
      iosConfig,
    ]
  }
  static func == (lhs: RaspConfigMessage, rhs: RaspConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsRaspApi(lhs.enabledThreats, rhs.enabledThreats) && deepEqualsRaspApi(lhs.exitThreats, rhs.exitThreats) && deepEqualsRaspApi(lhs.monitoringIntervalMs, rhs.monitoringIntervalMs) && deepEqualsRaspApi(lhs.androidConfig, rhs.androidConfig) && deepEqualsRaspApi(lhs.iosConfig, rhs.iosConfig)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RaspConfigMessage")
    deepHashRaspApi(value: enabledThreats, hasher: &hasher)
    deepHashRaspApi(value: exitThreats, hasher: &hasher)
    deepHashRaspApi(value: monitoringIntervalMs, hasher: &hasher)
    deepHashRaspApi(value: androidConfig, hasher: &hasher)
    deepHashRaspApi(value: iosConfig, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ThreatResultEntry: Hashable {
  var threatName: String
  var detected: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ThreatResultEntry? {
    let threatName = pigeonVar_list[0] as! String
    let detected = pigeonVar_list[1] as! Bool

    return ThreatResultEntry(
      threatName: threatName,
      detected: detected
    )
  }
  func toList() -> [Any?] {
    return [
      threatName,
      detected,
    ]
  }
  static func == (lhs: ThreatResultEntry, rhs: ThreatResultEntry) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsRaspApi(lhs.threatName, rhs.threatName) && deepEqualsRaspApi(lhs.detected, rhs.detected)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ThreatResultEntry")
    deepHashRaspApi(value: threatName, hasher: &hasher)
    deepHashRaspApi(value: detected, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScanResultMessage: Hashable {
  var results: [ThreatResultEntry]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScanResultMessage? {
    let results = pigeonVar_list[0] as! [ThreatResultEntry]

    return ScanResultMessage(
      results: results
    )
  }
  func toList() -> [Any?] {
    return [
      results
    ]
  }
  static func == (lhs: ScanResultMessage, rhs: ScanResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsRaspApi(lhs.results, rhs.results)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScanResultMessage")
    deepHashRaspApi(value: results, hasher: &hasher)
  }
}

private class RaspApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AndroidConfigMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return IosConfigMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return RaspConfigMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return ThreatResultEntry.fromList(self.readValue() as! [Any?])
    case 133:
      return ScanResultMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class RaspApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AndroidConfigMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? IosConfigMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? RaspConfigMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ThreatResultEntry {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ScanResultMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class RaspApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return RaspApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return RaspApiPigeonCodecWriter(data: data)
  }
}

class RaspApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = RaspApiPigeonCodec(readerWriter: RaspApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterRaspHostApi {
  func startMonitoring(config: RaspConfigMessage, completion: @escaping (Result<Void, Error>) -> Void)
  func stopMonitoring(completion: @escaping (Result<Void, Error>) -> Void)
  func checkThreat(threatName: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func scanAll(enabledThreats: [String], completion: @escaping (Result<ScanResultMessage, Error>) -> Void)
  func blockScreenCapture(enabled: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func isScreenCaptureBlocked(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterRaspHostApiSetup {
  static var codec: FlutterStandardMessageCodec { RaspApiPigeonCodec.shared }
  /// Sets up an instance of `FlutterRaspHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterRaspHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startMonitoringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.startMonitoring\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startMonitoringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! RaspConfigMessage
        api.startMonitoring(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startMonitoringChannel.setMessageHandler(nil)
    }
    let stopMonitoringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.stopMonitoring\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopMonitoringChannel.setMessageHandler { _, reply in
        api.stopMonitoring { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopMonitoringChannel.setMessageHandler(nil)
    }
    let checkThreatChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.checkThreat\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkThreatChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let threatNameArg = args[0] as! String
        api.checkThreat(threatName: threatNameArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkThreatChannel.setMessageHandler(nil)
    }
    let scanAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.scanAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanAllChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledThreatsArg = args[0] as! [String]
        api.scanAll(enabledThreats: enabledThreatsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      scanAllChannel.setMessageHandler(nil)
    }
    let blockScreenCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.blockScreenCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      blockScreenCaptureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        api.blockScreenCapture(enabled: enabledArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      blockScreenCaptureChannel.setMessageHandler(nil)
    }
    let isScreenCaptureBlockedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_rasp.FlutterRaspHostApi.isScreenCaptureBlocked\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isScreenCaptureBlockedChannel.setMessageHandler { _, reply in
        api.isScreenCaptureBlocked { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isScreenCaptureBlockedChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FlutterRaspFlutterApiProtocol {
  func onThreatsDetected(threats threatsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class FlutterRaspFlutterApi: FlutterRaspFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: RaspApiPigeonCodec {
    return RaspApiPigeonCodec.shared
  }
  func onThreatsDetected(threats threatsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_rasp.FlutterRaspFlutterApi.onThreatsDetected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([threatsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
